# Build Stage
FROM maven:3.9.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY src ./src

COPY pom.xml .

RUN mvn clean package -DskipTests

# Run Stage
FROM gcr.io/distroless/java17-debian12

WORKDIR /app

COPY --from=build /app/target/spring-demo-1.0.0.jar .

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "spring-demo-1.0.0.jar"]